version: "3.10"

services:
  fastapi:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs

  streamlit:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs