services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker api.main:app --bind=0.0.0.0:8000
    envVars:
      - key: PORT
        value: 8000
    runtime: python
    branch: master
    autoDeploy: true

  - type: web
    name: streamlit-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/main.py --server.port=8501 --server.address=0.0.0.0
    runtime: python
    branch: master
    autoDeploy: true
